services:
  odoo:
    container_name: {{ cookiecutter.project_slug }}
    command: odoo --dev=all
    {% if cookiecutter.debug != 'n' %}
    build:
      context: .
      dockerfile: odoo.Dockerfile
    {% else %}
    image: odoo:{{ cookiecutter.odoo_version }}
    {% endif %}
    depends_on:
      - db
    ports:
      - "${ODOO_EXT_PORT}:8069"
    volumes:
      - odoo:/var/lib/odoo
      - ./config:/etc/odoo:z
      - ./addons:/mnt/custom-addons:z
    # restart: unless-stopped
  db:
    container_name: {{ cookiecutter.project_slug }}_db
    {% if cookiecutter.odoo_version == '19.0' %}
    build:
      context: .
      dockerfile: postgres.Dockerfile
    {% else %}
    image: postgres:{{ cookiecutter.postgresql_version }}
    {% endif %}
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    ports:
      - "${POSTGRES_EXT_PORT}:5432"
    volumes:
        - db:/var/lib/postgresql/data
        {% if cookiecutter.odoo_version == '19.0' %}
        - ./config/init-pgvector.sql:/docker-entrypoint-initdb.d/init-pgvector.sql
        {% endif %}
    # restart: unless-stopped
{% if cookiecutter.include_pg_admin == 'y' %}
  pgadmin:
    container_name: {{ cookiecutter.project_slug }}_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: josevizcaya0616@gmail.com
      PGADMIN_DEFAULT_PASSWORD: odoo
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
        - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_EXT_PORT}:80"
    # restart: unless-stopped
{% endif %}

volumes:
  odoo:
  db:
{% if cookiecutter.include_pg_admin == 'y' %}
  pgadmin:
{% endif %}
